//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Circus.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SheduleTrainers
    {
        public int IDSheduleTraineres { get; set; }
        public Nullable<int> IDCell { get; set; }
        public Nullable<System.DateTime> DateOfTrainer { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<bool> Done { get; set; }
        public string Description { get; set; }
    
        public virtual Cell Cell { get; set; }
    }
}
